use std::path::PathBuf;

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub enum PlannedOp {
    Delete { path: PathBuf },
    Move { from: PathBuf, to: PathBuf },
    Copy { from: PathBuf, to: PathBuf },
    Mkdir { path: PathBuf },
    Rename { from: PathBuf, to: String },
}

#[derive(Clone, Debug)]
#[allow(dead_code)]
pub enum Command {
    Quit,
    SwitchPanel,
    CursorUp,
    CursorDown,
    PageUp,
    PageDown,
    Navigate,
    GoParent,
    ToggleSelect,
    SelectAll,
    ClearSelection,
    ShowHelp,
    Copy,
    Move,
    Delete,
    Pack,
    Mkdir,
    Rename,
    Find,
    Filter,
    QuickSearch(char),
    Sort,
    Refresh,
    ToggleHidden,
    ToggleWrap,
    View,
    ConfirmDialog,
    CancelDialog,
    DialogInput(char),
    DialogBackspace,
    DialogLeft,
    DialogRight,
    SearchInput(char),
    SearchBackspace,
    SearchConfirm,
    SearchConfirmResults(Vec<crate::fs::FileEntry>),
    SearchCancel,
    UpdateTotalSize(bool, u64),
    ViewerTailUpdate(String),
    AiSummarize,
    AiSecurityScan,
    AiImageInfo,
    AiCodeStructure,
    AiFileDiff,
    AiFolderAnalysis,
    AiFindDuplicates,
    AiOldFiles,
    AiFileClassify,
    AiStorageOptimize,
    AiGitHistory,
    AiGenerateReadme,
    AiAddNote,
    AiGenerateScript,
    SaveNote(String),
    AiQuery(String),
    AiResponse(crate::ai::AiResponse),
    AiError(String),
    AiCancel,
    AiScrollUp,
    AiScrollDown,
    AiPageUp,
    AiPageDown,
    AiToggleThinking,
    AiNaturalCommand,
    BatchRename,
    AiCommandParsed(Vec<PlannedOp>),
    AiCommandConfirm,
    AiCommandCancel,
    AiCommandScrollUp,
    AiCommandScrollDown,
    DuplicatesResult(String),
    OldFilesResult(String),
    ClassifyResult(String),
    StorageResult(String),
    GitHistoryResult(String),
    AiFolderSync,
    SyncResult(String),
    MacroRecord,
    MacroList,
    MacroRun,
    AiNextAction,
    None,
}
